name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Fetch
      uses: actions/checkout@master
    - uses: actions/checkout@v2
    - name: compile and test
      run: | 
        cd LR7_Z6.2_V27/
        g++ -ftest-coverage -fprofile-arcs -O0 -o test test.cpp interpol.cpp
        ./test
        gcov -abcfu interpol.cpp
    - name: Upload
      uses: codecov/codecov-action@v1
      with: 
       files: |
         ./LR7_Z6.2_V27/interpol.cpp.gcov
