name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          cd ./2_semester/LR7_Z6.2_V27
          g++ -ftest-coverage -fprofile-arcs -O0 -o test test.cpp crime.cpp criminal.cpp organization.cpp utilities.cpp interpol.cpp
          ./test
          gcov -abcfu crime.cpp criminal.cpp organization.cpp utilities.cpp interpol.cpp
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: |
                 ./2_semester/LR7_Z6.2_V27/crime.cpp.gcov
                 ./2_semester/LR7_Z6.2_V27/criminal.cpp.gcov
                 ./2_semester/LR7_Z6.2_V27/organization.cpp.gcov
                 ./2_semester/LR7_Z6.2_V27/utilities.cpp.gcov
                 ./2_semester/LR7_Z6.2_V27/interpol.cpp.gcov
